#!/usr/bin/env bash
set -euo pipefail

repo_root="/home/kyo/Projects/hyprland-settings"
evidence_root="${1:-/tmp/hyprland-settings-gtk-automation/$(date +%Y%m%d_%H%M%S)}"
scenario_root="$evidence_root/scenarios"
run_root="$evidence_root/runs"

mkdir -p "$scenario_root" "$run_root"

write_conf() {
  local scenario="$1"
  shift
  local home="$scenario_root/$scenario"
  mkdir -p "$home/.config/hypr"
  printf '%s\n' "$@" > "$home/.config/hypr/hyprland.conf"
}

write_conf minimal_single_config \
  'decoration:blur:enabled = true' \
  'misc:disable_hyprland_logo = true'

write_conf source_include_config \
  'source = appearance.conf' \
  'source = input.conf'
printf '%s\n' 'decoration:blur:enabled = true' > "$scenario_root/source_include_config/.config/hypr/appearance.conf"
printf '%s\n' 'input:follow_mouse = 1' > "$scenario_root/source_include_config/.config/hypr/input.conf"

write_conf nested_source_config \
  'source = profiles/current.conf'
mkdir -p "$scenario_root/nested_source_config/.config/hypr/profiles" \
  "$scenario_root/nested_source_config/.config/hypr/appearance"
printf '%s\n' 'source = ../appearance/theme.conf' > "$scenario_root/nested_source_config/.config/hypr/profiles/current.conf"
printf '%s\n' 'decoration:blur:enabled = true' > "$scenario_root/nested_source_config/.config/hypr/appearance/theme.conf"

write_conf duplicate_conflict \
  'decoration:blur:enabled = true' \
  'source = appearance.conf'
printf '%s\n' 'decoration:blur:enabled = false' > "$scenario_root/duplicate_conflict/.config/hypr/appearance.conf"

write_conf missing_default_only \
  '# minimal default-like config intentionally leaves most scalar settings unset'

write_conf high_risk_display_risk \
  'decoration:screen_shader = /tmp/fake.frag' \
  'render:direct_scanout = false'

write_conf generated_config \
  '# generated by fixture' \
  '# do not edit' \
  'decoration:blur:enabled = true'

write_conf script_managed_config \
  'source = managed.conf'
printf '%s\n' 'decoration:blur:enabled = true' > "$scenario_root/script_managed_config/.config/hypr/managed.conf"
mkdir -p "$scenario_root/script_managed_config/.config/hypr/scripts"
printf '%s\n' '#!/usr/bin/env sh' 'sed -i s/true/false/ ../managed.conf' 'hyprctl reload' > "$scenario_root/script_managed_config/.config/hypr/scripts/manage.sh"

write_conf symlink_current_profile \
  'source = current.conf'
printf '%s\n' 'decoration:blur:enabled = true' > "$scenario_root/symlink_current_profile/.config/hypr/desktop.conf"
ln -s desktop.conf "$scenario_root/symlink_current_profile/.config/hypr/current.conf"

run_probe() {
  local scenario="$1"
  local target="$2"
  local home="$scenario_root/$scenario"
  local evidence_dir="$run_root/${scenario}_${target// /}"
  mkdir -p "$evidence_dir"
  HYPR_SETTINGS_ATSPI_NAV_TARGET="$target" \
    "$repo_root/tools/live_scenario_harness/gtk_automation_probe.sh" "$home" "$evidence_dir"
}

cd "$repo_root"
run_probe minimal_single_config Dashboard
run_probe minimal_single_config Config
run_probe minimal_single_config "Safety Details"
run_probe generated_config "Safety Details"
run_probe script_managed_config "Safety Details"
run_probe symlink_current_profile "Safety Details"
run_probe minimal_single_config Appearance
run_probe high_risk_display_risk Display
run_probe source_include_config Config
run_probe nested_source_config Config
run_probe duplicate_conflict Appearance
run_probe duplicate_conflict DuplicateConflictDetail
run_probe missing_default_only Appearance
run_probe missing_default_only MissingDefaultDetail
run_probe generated_config Config
run_probe generated_config GeneratedConnectedFileDetail
run_probe script_managed_config Config
run_probe script_managed_config ScriptManagedConnectedFileDetail
run_probe symlink_current_profile Config
run_probe symlink_current_profile SymlinkConnectedFileDetail
run_probe symlink_current_profile ProfileModeDetail
run_probe minimal_single_config Search
run_probe minimal_single_config DetailPane
run_probe minimal_single_config DeadManPreviewDetail
run_probe minimal_single_config InputProofDetail
run_probe minimal_single_config FirstBlockedSettingRow
run_probe high_risk_display_risk HighRiskDetail
run_probe high_risk_display_risk DisplayRenderRiskDetail

"$repo_root/tools/live_scenario_harness/summarize_gtk_evidence.py" \
  "$evidence_root" \
  "$evidence_root/gtk-evidence-summary.json" \
  "$repo_root/data/reports"

printf '%s\n' "$evidence_root"
