use std::fs;

use hyprland_settings::production_advanced_confirmation::disabled_advanced_confirmation_ui_lines;
use hyprland_settings::write_classification::SAFE_WRITABLE_ROWS;

#[test]
fn disabled_advanced_confirmation_copy_exists_without_handlers() {
    let window = fs::read_to_string("src/ui/window.rs").expect("window source should read");
    let section = window
        .split("Production backup and verification")
        .nth(1)
        .and_then(|section| section.split("Review save location").next())
        .expect("production backup and advanced confirmation section should exist");
    let lines = disabled_advanced_confirmation_ui_lines();

    for copy in [
        "Advanced confirmation",
        "Some files may be changed by scripts, generated by tools, or managed through symlinks.",
        "These targets are excluded from the first production write pilot.",
        "Advanced confirmation is not active yet.",
        "Real writing is not active yet.",
        "Apply behavior has not changed.",
    ] {
        assert!(lines.iter().any(|line| line == copy));
    }
    assert!(window.contains("disabled_advanced_confirmation_ui_lines"));
    assert!(!section.contains("connect_clicked"));
    assert!(!section.contains("apply_setting_change("));
    assert_eq!(SAFE_WRITABLE_ROWS.len(), 341);
}
