use std::fs;
use std::path::{Path, PathBuf};

use hyprland_settings::write_classification::SAFE_WRITABLE_ROWS;
use hyprland_settings::write_target_candidate::WriteTargetCandidate;
use hyprland_settings::write_target_fixture_proof::{
    prove_fixture_target_write, FixtureTargetWriteProofError, FixtureTargetWriteProofRequest,
};

fn temp_fixture(name: &str) -> PathBuf {
    let root = std::env::temp_dir().join(format!(
        "hyprland-settings-fixture-proof-{name}-{}",
        std::process::id()
    ));
    let _ = fs::remove_dir_all(&root);
    fs::create_dir_all(&root).expect("fixture root should be created");
    root
}

fn write_file(path: &Path, content: &str) {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).expect("fixture parent should be created");
    }
    fs::write(path, content).expect("fixture file should be written");
}

fn target(path: PathBuf, line_number: usize, generated: bool) -> WriteTargetCandidate {
    WriteTargetCandidate {
        label: "Fixture target".to_string(),
        file_path: path,
        resolved_path: None,
        line_number: Some(line_number),
        safe: !generated,
        generated_or_script_managed: generated,
        requires_advanced_confirmation: generated,
        backup_required: true,
        fixture_only: true,
    }
}

#[test]
fn fixture_target_can_be_backed_up_written_reread_and_verified() {
    let root = temp_fixture("success");
    let config = root.join("hyprland.conf");
    write_file(
        &config,
        "# keep this\nwindowrule = float, class:test\ngeneral:layout = dwindle\nmisc:disable_hyprland_logo = true\n",
    );

    let proof = prove_fixture_target_write(&FixtureTargetWriteProofRequest {
        target: target(config.clone(), 3, false),
        setting_id: "general.layout".to_string(),
        new_value: "master".to_string(),
        advanced_fixture_approval: false,
    })
    .expect("fixture proof should pass");

    assert!(proof.fixture_only);
    assert!(proof.backup_path.exists());
    assert_eq!(proof.target_path, config);
    assert_eq!(proof.reread_value.as_deref(), Some("master"));
    assert!(proof.unrelated_lines_preserved);
    let updated = fs::read_to_string(&proof.target_path).expect("updated fixture should read");
    assert!(updated.contains("# keep this"));
    assert!(updated.contains("windowrule = float, class:test"));
    assert!(updated.contains("misc:disable_hyprland_logo = true"));
    assert!(updated.contains("general:layout = master"));
    assert!(!proof.target_path.starts_with("/home/kyo/.config/hypr"));
    assert_eq!(SAFE_WRITABLE_ROWS.len(), 341);
}

#[test]
fn generated_fixture_target_requires_advanced_fixture_approval() {
    let root = temp_fixture("generated");
    let config = root.join("generated.conf");
    write_file(
        &config,
        "# generated by test\n# do not edit\ngeneral:layout = dwindle\n",
    );

    let request = FixtureTargetWriteProofRequest {
        target: target(config.clone(), 3, true),
        setting_id: "general.layout".to_string(),
        new_value: "master".to_string(),
        advanced_fixture_approval: false,
    };
    let error = prove_fixture_target_write(&request).expect_err("unsafe target should reject");
    assert_eq!(
        error,
        FixtureTargetWriteProofError::UnsafeTargetRequiresAdvancedApproval
    );

    let approved = prove_fixture_target_write(&FixtureTargetWriteProofRequest {
        advanced_fixture_approval: true,
        ..request
    })
    .expect("advanced fixture approval should allow fixture-only proof");
    assert_eq!(approved.reread_value.as_deref(), Some("master"));
}

#[test]
fn production_apply_path_remains_unchanged_by_fixture_proof() {
    let source = fs::read_to_string("src/write_flow.rs").expect("write flow source should read");
    assert!(!source.contains("prove_fixture_target_write"));
    assert!(!source.contains("FixtureTargetWriteProofRequest"));
}
