use std::fs;
use std::path::{Path, PathBuf};

use hyprland_settings::config_graph::{
    inspect_config_graph_with_options, ConfigGraphOptions, SourceFollowPolicy,
};
use hyprland_settings::config_layered_values::layered_values_for_setting;
use hyprland_settings::guarded_write_review::{
    build_guarded_write_target_review, FixtureProofStatus, GuardedWriteReviewStatus,
};
use hyprland_settings::write_advanced_confirmation::advanced_confirmation_for_candidate;
use hyprland_settings::write_backup_plan::build_exact_backup_plan;
use hyprland_settings::write_classification::SAFE_WRITABLE_ROWS;
use hyprland_settings::write_target_candidate::write_target_candidates_for_layered_setting;
use hyprland_settings::write_target_fixture_proof::{
    prove_fixture_target_write, FixtureTargetWriteProofError, FixtureTargetWriteProofRequest,
};
use hyprland_settings::write_target_recommendation::recommend_write_targets;
use hyprland_settings::write_verification_plan::{
    fixture_verification_passed, planned_reread_verification, WriteVerificationStatus,
};

fn temp_fixture(name: &str) -> PathBuf {
    let root = std::env::temp_dir().join(format!(
        "hyprland-settings-guarded-review-{name}-{}",
        std::process::id()
    ));
    let _ = fs::remove_dir_all(&root);
    fs::create_dir_all(&root).expect("fixture root should be created");
    root
}

fn write_file(path: &Path, content: &str) {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).expect("fixture parent should be created");
    }
    fs::write(path, content).expect("fixture file should be written");
}

#[test]
fn fixture_backed_review_proof_runs_end_to_end_without_real_config_paths() {
    let root = temp_fixture("end-to-end");
    let config = root.join("hyprland.conf");
    let desktop = root.join("profiles/desktop.conf");
    write_file(
        &config,
        "source = profiles/desktop.conf\n# keep root line\ngeneral:layout = dwindle\n",
    );
    write_file(
        &desktop,
        "# keep profile line\ngeneral:layout = dwindle\nmisc:disable_hyprland_logo = true\n",
    );

    let graph = inspect_config_graph_with_options(
        &config,
        ConfigGraphOptions {
            home_dir: Some(root.clone()),
            script_dirs: Vec::new(),
            max_depth: 16,
            source_follow_policy: SourceFollowPolicy::ReviewAll,
        },
    );
    let layered = layered_values_for_setting(&graph, "general.layout");
    let candidates = write_target_candidates_for_layered_setting(&layered, &graph.files);
    let recommendation = recommend_write_targets(&candidates);
    let selected = recommendation
        .other_possible_targets
        .iter()
        .find(|candidate| candidate.label == "Profile file")
        .cloned()
        .or_else(|| recommendation.recommended_target.clone())
        .expect("a fixture target should be available");

    let backup_plan = build_exact_backup_plan(&selected);
    let advanced_confirmation = advanced_confirmation_for_candidate(&selected);
    let verification_plan = planned_reread_verification(&selected, "general.layout", "master");
    let proof = prove_fixture_target_write(&FixtureTargetWriteProofRequest {
        target: selected.clone(),
        setting_id: "general.layout".to_string(),
        new_value: "master".to_string(),
        advanced_fixture_approval: false,
    })
    .expect("safe fixture target should write and reread");
    let verification_passed = fixture_verification_passed(&verification_plan);
    let guarded_review = build_guarded_write_target_review(
        "windows.layout",
        "general.layout",
        "master",
        Some("dwindle".to_string()),
        Some("dwindle".to_string()),
        &recommendation,
        Some(selected.clone()),
        true,
        FixtureProofStatus::Passed,
    );

    assert!(backup_plan.fixture_only);
    assert!(backup_plan.production_backup_disabled);
    assert!(advanced_confirmation.production_disabled);
    assert_eq!(
        verification_passed.verification_status,
        WriteVerificationStatus::PassedInFixture
    );
    assert_eq!(proof.reread_value.as_deref(), Some("master"));
    assert!(proof.unrelated_lines_preserved);
    assert!(!proof.target_path.starts_with("/home/kyo/.config/hypr"));
    assert_eq!(
        guarded_review.review_status,
        GuardedWriteReviewStatus::ReadyForReview
    );
    assert!(
        guarded_review
            .required_gates
            .production_write_integration_allowed
    );
    assert_eq!(SAFE_WRITABLE_ROWS.len(), 341);
}

#[test]
fn generated_target_requires_advanced_fixture_approval_for_fixture_proof() {
    let root = temp_fixture("generated");
    let config = root.join("hyprland.conf");
    let generated = root.join("profiles/gaming.conf");
    write_file(
        &config,
        "source = profiles/gaming.conf\ngeneral:layout = dwindle\n",
    );
    write_file(
        &generated,
        "# generated by test\n# do not edit\ngeneral:layout = dwindle\n",
    );

    let graph = inspect_config_graph_with_options(
        &config,
        ConfigGraphOptions {
            home_dir: Some(root.clone()),
            script_dirs: Vec::new(),
            max_depth: 16,
            source_follow_policy: SourceFollowPolicy::ReviewAll,
        },
    );
    let layered = layered_values_for_setting(&graph, "general.layout");
    let candidates = write_target_candidates_for_layered_setting(&layered, &graph.files);
    let generated_target = candidates
        .iter()
        .find(|candidate| candidate.generated_or_script_managed)
        .cloned()
        .expect("generated target should be represented");

    let rejected = prove_fixture_target_write(&FixtureTargetWriteProofRequest {
        target: generated_target.clone(),
        setting_id: "general.layout".to_string(),
        new_value: "master".to_string(),
        advanced_fixture_approval: false,
    })
    .expect_err("generated target needs advanced fixture approval");
    assert_eq!(
        rejected,
        FixtureTargetWriteProofError::UnsafeTargetRequiresAdvancedApproval
    );

    let approved = prove_fixture_target_write(&FixtureTargetWriteProofRequest {
        target: generated_target,
        setting_id: "general.layout".to_string(),
        new_value: "master".to_string(),
        advanced_fixture_approval: true,
    })
    .expect("advanced fixture approval allows fixture-only proof");
    assert_eq!(approved.reread_value.as_deref(), Some("master"));
}
