use std::fs;
use std::path::{Path, PathBuf};

use hyprland_settings::config_graph::{
    inspect_config_graph_with_options, ConfigGraphOptions, SourceFollowPolicy,
};
use hyprland_settings::config_layered_values::layered_values_for_setting;
use hyprland_settings::write_classification::SAFE_WRITABLE_ROWS;

fn temp_fixture(name: &str) -> PathBuf {
    let root = std::env::temp_dir().join(format!(
        "hyprland-settings-layered-occurrences-{name}-{}",
        std::process::id()
    ));
    let _ = fs::remove_dir_all(&root);
    fs::create_dir_all(&root).expect("fixture root should be created");
    root
}

fn write_file(path: &Path, content: &str) {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).expect("fixture parent should be created");
    }
    fs::write(path, content).expect("fixture file should be written");
}

#[cfg(unix)]
fn symlink_file(target: &Path, link: &Path) {
    std::os::unix::fs::symlink(target, link).expect("fixture symlink should be created");
}

#[test]
fn layered_occurrence_details_flag_generated_script_and_symlink_context() {
    let root = temp_fixture("flags");
    let config = root.join("hyprland.conf");
    let desktop = root.join("profiles/desktop.conf");
    let generated = root.join("profiles/gaming.conf");
    let current = root.join("profiles/current.conf");
    write_file(
        &config,
        "source = profiles/current.conf\nsource = profiles/gaming.conf\ngeneral:layout = dwindle\n",
    );
    write_file(&desktop, "general:layout = master\n");
    write_file(
        &generated,
        "# generated by game mode\n# do not edit\ngeneral:layout = dwindle\n",
    );
    #[cfg(unix)]
    symlink_file(&desktop, &current);
    #[cfg(not(unix))]
    write_file(&current, "general:layout = master\n");

    let script_dir = root.join("scripts");
    write_file(
        &script_dir.join("mode.sh"),
        "ln -sf profiles/desktop.conf profiles/current.conf\nhyprctl reload\n",
    );

    let graph = inspect_config_graph_with_options(
        &config,
        ConfigGraphOptions {
            home_dir: Some(root.clone()),
            script_dirs: vec![script_dir],
            max_depth: 16,
            source_follow_policy: SourceFollowPolicy::ReviewAll,
        },
    );
    let layered = layered_values_for_setting(&graph, "general.layout");

    assert!(layered.controlled_in_more_than_one_place);
    assert!(layered
        .occurrences
        .iter()
        .any(|occurrence| occurrence.generated_or_script_managed));
    assert!(layered
        .occurrences
        .iter()
        .any(|occurrence| occurrence.symlink_managed));
    let lines = layered.display_lines();
    assert!(lines
        .iter()
        .any(|line| line.contains("This file may be changed by scripts")));
    assert!(lines.iter().any(|line| line.contains("symlinked")));
    assert!(layered
        .occurrences
        .iter()
        .all(|occurrence| occurrence.read_only));
    assert_eq!(SAFE_WRITABLE_ROWS.len(), 341);
}

#[test]
fn structured_entries_do_not_create_layered_scalar_occurrences() {
    let root = temp_fixture("structured");
    let config = root.join("hyprland.conf");
    let profile = root.join("profiles/desktop.conf");
    write_file(
        &config,
        "source = profiles/desktop.conf\nmonitor = eDP-1,preferred,auto,1\n",
    );
    write_file(&profile, "monitor = HDMI-A-1,preferred,auto,1\n");

    let graph = inspect_config_graph_with_options(
        &config,
        ConfigGraphOptions {
            home_dir: Some(root.clone()),
            script_dirs: Vec::new(),
            max_depth: 16,
            source_follow_policy: SourceFollowPolicy::ReviewAll,
        },
    );

    let layered = layered_values_for_setting(&graph, "hl.monitor");
    assert!(layered.occurrences.is_empty());
    assert!(!layered.controlled_in_more_than_one_place);
}
