use std::fs;
use std::path::{Path, PathBuf};

use hyprland_settings::config_selection::SourceFollowChoice;
use hyprland_settings::session_config_preview::build_session_config_preview;

fn temp_fixture(name: &str) -> PathBuf {
    let root = std::env::temp_dir().join(format!(
        "hyprland-settings-session-preview-read-{name}-{}",
        std::process::id()
    ));
    let _ = fs::remove_dir_all(&root);
    fs::create_dir_all(&root).expect("fixture root should be created");
    root
}

fn write_file(path: &Path, content: &str) {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).expect("fixture parent should be created");
    }
    fs::write(path, content).expect("fixture file should be written");
}

#[test]
fn session_preview_respects_review_all_connected_files() {
    let root = temp_fixture("all");
    let config = root.join("hyprland.conf");
    let profile = root.join("profiles/desktop.conf");
    write_file(
        &config,
        "source = profiles/desktop.conf\ndecoration:blur:enabled = false\n",
    );
    write_file(&profile, "decoration:blur:enabled = true\n");

    let preview =
        build_session_config_preview(&config, SourceFollowChoice::ReviewAllConnectedFiles);

    assert_eq!(preview.graph.connected_file_count, 2);
    assert_eq!(preview.readable_file_count, 2);
    assert_eq!(preview.scalar_value_count, 2);
    assert_eq!(preview.settings_with_multiple_locations, 1);
    assert!(preview
        .user_facing_lines()
        .iter()
        .any(|line| line == "Settings with multiple locations: 1"));
}

#[test]
fn session_preview_respects_only_selected_file() {
    let root = temp_fixture("only");
    let config = root.join("hyprland.conf");
    let profile = root.join("profiles/desktop.conf");
    write_file(
        &config,
        "source = profiles/desktop.conf\ndecoration:blur:enabled = false\n",
    );
    write_file(&profile, "decoration:blur:enabled = true\n");

    let preview = build_session_config_preview(&config, SourceFollowChoice::OnlySelectedFile);
    let lines = preview.user_facing_lines();

    assert_eq!(preview.graph.connected_file_count, 1);
    assert_eq!(preview.readable_file_count, 1);
    assert_eq!(preview.scalar_value_count, 1);
    assert_eq!(preview.settings_with_multiple_locations, 0);
    assert!(lines
        .iter()
        .any(|line| line == "Connected files are not included in this session preview."));
}

#[test]
fn generated_and_script_managed_hints_are_reported_without_writes() {
    let root = temp_fixture("generated");
    let config = root.join("hyprland.conf");
    write_file(
        &config,
        "# generated by test\n# do not edit\ngeneral:layout = dwindle\n",
    );

    let preview =
        build_session_config_preview(&config, SourceFollowChoice::ReviewAllConnectedFiles);

    assert!(preview.generated_or_script_managed_hints);
    assert!(preview
        .user_facing_lines()
        .iter()
        .any(|line| line == "Generated/script-managed hints: detected"));
    assert!(!preview.affects_writes);
}
