use std::fs;
use std::path::{Path, PathBuf};

use hyprland_settings::config_graph::{
    inspect_config_graph_with_options, ConfigGraphOptions, SourceFollowPolicy,
};
use hyprland_settings::config_layered_values::layered_values_for_setting;
use hyprland_settings::write_classification::SAFE_WRITABLE_ROWS;
use hyprland_settings::write_target_candidate::write_target_candidates_for_layered_setting;
use hyprland_settings::write_target_recommendation::recommend_write_targets;

fn temp_fixture(name: &str) -> PathBuf {
    let root = std::env::temp_dir().join(format!(
        "hyprland-settings-write-recommendations-{name}-{}",
        std::process::id()
    ));
    let _ = fs::remove_dir_all(&root);
    fs::create_dir_all(&root).expect("fixture root should be created");
    root
}

fn write_file(path: &Path, content: &str) {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).expect("fixture parent should be created");
    }
    fs::write(path, content).expect("fixture file should be written");
}

#[test]
fn disabled_write_target_recommendation_model_represents_safe_and_blocked_targets() {
    let root = temp_fixture("model");
    let config = root.join("hyprland.conf");
    let desktop = root.join("profiles/desktop.conf");
    let generated = root.join("profiles/gaming.conf");
    write_file(
        &config,
        "source = profiles/desktop.conf\nsource = profiles/gaming.conf\ngeneral:layout = dwindle\n",
    );
    write_file(&desktop, "general:layout = master\n");
    write_file(
        &generated,
        "# generated by game mode\n# do not edit\ngeneral:layout = dwindle\n",
    );

    let graph = inspect_config_graph_with_options(
        &config,
        ConfigGraphOptions {
            home_dir: Some(root.clone()),
            script_dirs: Vec::new(),
            max_depth: 16,
            source_follow_policy: SourceFollowPolicy::ReviewAll,
        },
    );
    let layered = layered_values_for_setting(&graph, "general.layout");
    let candidates = write_target_candidates_for_layered_setting(&layered, &graph.files);
    let recommendation = recommend_write_targets(&candidates);

    assert!(recommendation.recommended_target.is_some());
    assert!(!recommendation.other_possible_targets.is_empty());
    assert_eq!(recommendation.blocked_targets.len(), 1);
    assert!(recommendation.advanced_confirmation_required);
    assert!(recommendation.backup_required);
    assert!(recommendation.fixture_only);
    assert!(recommendation.production_disabled);
    assert!(recommendation
        .user_facing_lines()
        .iter()
        .any(|line| line == "Real write-target selection is not active yet."));
    assert_eq!(SAFE_WRITABLE_ROWS.len(), 341);
}
