use std::fs;
use std::path::{Path, PathBuf};

use hyprland_settings::config_graph::{
    inspect_config_graph_with_options, ConfigGraphOptions, ConfigManagementHintKind,
    SourceFollowPolicy,
};
use hyprland_settings::config_layered_values::layered_values_for_setting;
use hyprland_settings::write_classification::SAFE_WRITABLE_ROWS;
use hyprland_settings::write_target_candidate::write_target_candidates_for_layered_setting;

fn temp_fixture(name: &str) -> PathBuf {
    let root = std::env::temp_dir().join(format!(
        "hyprland-settings-write-targets-{name}-{}",
        std::process::id()
    ));
    let _ = fs::remove_dir_all(&root);
    fs::create_dir_all(&root).expect("fixture root should be created");
    root
}

fn write_file(path: &Path, content: &str) {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).expect("fixture parent should be created");
    }
    fs::write(path, content).expect("fixture file should be written");
}

#[test]
fn write_target_candidates_are_generated_from_fixture_layered_values() {
    let root = temp_fixture("candidates");
    let config = root.join("hyprland.conf");
    let desktop = root.join("profiles/desktop.conf");
    let gaming = root.join("profiles/gaming.conf");
    write_file(
        &config,
        "source = profiles/desktop.conf\nsource = profiles/gaming.conf\ngeneral:layout = dwindle\n",
    );
    write_file(&desktop, "general:layout = master\n");
    write_file(
        &gaming,
        "# generated by game mode\n# do not edit\ngeneral:layout = dwindle\n",
    );

    let graph = inspect_config_graph_with_options(
        &config,
        ConfigGraphOptions {
            home_dir: Some(root.clone()),
            script_dirs: Vec::new(),
            max_depth: 16,
            source_follow_policy: SourceFollowPolicy::ReviewAll,
        },
    );
    let layered = layered_values_for_setting(&graph, "general.layout");
    let candidates = write_target_candidates_for_layered_setting(&layered, &graph.files);

    assert_eq!(candidates.len(), 3);
    assert!(candidates
        .iter()
        .any(|candidate| candidate.label == "Main config"));
    assert!(candidates
        .iter()
        .any(|candidate| candidate.label == "Desktop profile"));
    let generated = candidates
        .iter()
        .find(|candidate| candidate.label == "Gaming profile")
        .expect("gaming profile target should be represented");
    assert!(!generated.safe);
    assert!(generated.generated_or_script_managed);
    assert!(generated.requires_advanced_confirmation);
    assert!(generated.backup_required);
    assert!(generated.fixture_only);
    assert_eq!(SAFE_WRITABLE_ROWS.len(), 341);

    let gaming_file = graph
        .files
        .iter()
        .find(|file| file.path == gaming)
        .expect("gaming file should be present");
    assert!(gaming_file
        .hints
        .iter()
        .any(|hint| hint.kind == ConfigManagementHintKind::GeneratedFile));
}
