//! GENERATED official default values for the 341 scalar options, from the
//! pinned trusted capture `data/exports/hyprland-0.55.4/hyprctl-descriptions.v0.55.4.json`
//! (live `hyprctl -j descriptions`, zero drift against v0.55.2 — see the
//! migration audit). Regenerate with the JSON-to-table snippet in the
//! pending-changes implementation report if the capture changes.
//!
//! Presentation only: unset rows seed their controls from the official
//! default instead of the edit projection's flip-suggestion, so a switch
//! never renders an inverted state for a value the user has not set.

/// The official default value for an official setting key (dot form), when
/// the trusted capture provides one.
pub fn official_default_value(official_setting: &str) -> Option<&'static str> {
    OFFICIAL_DEFAULTS
        .binary_search_by(|(key, _)| key.cmp(&official_setting))
        .ok()
        .map(|index| OFFICIAL_DEFAULTS[index].1)
}

const OFFICIAL_DEFAULTS: &[(&str, &str)] = &[
    ("animations.enabled", "true"),
    ("animations.workspace_wraparound", "false"),
    ("binds.allow_pin_fullscreen", "false"),
    ("binds.allow_workspace_cycles", "false"),
    ("binds.disable_keybind_grabbing", "false"),
    ("binds.drag_threshold", "0"),
    ("binds.focus_preferred_method", "0"),
    ("binds.hide_special_on_workspace_change", "false"),
    ("binds.ignore_group_lock", "false"),
    ("binds.movefocus_cycles_fullscreen", "false"),
    ("binds.movefocus_cycles_groupfirst", "false"),
    ("binds.pass_mouse_when_bound", "false"),
    ("binds.scroll_event_delay", "300"),
    ("binds.window_direction_monitor_fallback", "true"),
    ("binds.workspace_back_and_forth", "false"),
    ("binds.workspace_center_on", "1"),
    ("cursor.default_monitor", "[[EMPTY]]"),
    ("cursor.enable_hyprcursor", "true"),
    ("cursor.hide_on_key_press", "false"),
    ("cursor.hide_on_tablet", "false"),
    ("cursor.hide_on_touch", "true"),
    ("cursor.hotspot_padding", "0"),
    ("cursor.inactive_timeout", "0"),
    ("cursor.invisible", "false"),
    ("cursor.min_refresh_rate", "24"),
    ("cursor.no_break_fs_vrr", "2"),
    ("cursor.no_hardware_cursors", "2"),
    ("cursor.no_warps", "false"),
    ("cursor.persistent_warps", "false"),
    ("cursor.sync_gsettings_theme", "true"),
    ("cursor.use_cpu_buffer", "2"),
    ("cursor.warp_back_after_non_mouse_input", "false"),
    ("cursor.warp_on_change_workspace", "0"),
    ("cursor.warp_on_toggle_special", "0"),
    ("cursor.zoom_detached_camera", "true"),
    ("cursor.zoom_disable_aa", "false"),
    ("cursor.zoom_factor", "1"),
    ("cursor.zoom_rigid", "false"),
    ("debug.colored_stdout_logs", "true"),
    ("debug.damage_blink", "false"),
    ("debug.damage_tracking", "2"),
    ("debug.disable_logs", "true"),
    ("debug.disable_scale_checks", "false"),
    ("debug.disable_time", "true"),
    ("debug.ds_handle_same_buffer", "true"),
    ("debug.ds_handle_same_buffer_fifo", "true"),
    ("debug.enable_stdout_logs", "false"),
    ("debug.error_limit", "5"),
    ("debug.error_position", "0"),
    ("debug.fifo_pending_workaround", "false"),
    ("debug.full_cm_proto", "false"),
    ("debug.gl_debugging", "false"),
    ("debug.invalidate_fp16", "1"),
    ("debug.log_damage", "false"),
    ("debug.manual_crash", "0"),
    ("debug.overlay", "false"),
    ("debug.pass", "false"),
    ("debug.render_solitary_wo_damage", "false"),
    ("debug.suppress_errors", "false"),
    ("debug.vfr", "true"),
    ("decoration.active_opacity", "1"),
    ("decoration.blur.brightness", "1"),
    ("decoration.blur.contrast", "0.8916"),
    ("decoration.blur.enabled", "true"),
    ("decoration.blur.ignore_opacity", "true"),
    ("decoration.blur.input_methods", "false"),
    ("decoration.blur.input_methods_ignorealpha", "0.2"),
    ("decoration.blur.new_optimizations", "true"),
    ("decoration.blur.noise", "0.0117"),
    ("decoration.blur.passes", "1"),
    ("decoration.blur.popups", "false"),
    ("decoration.blur.popups_ignorealpha", "0.2"),
    ("decoration.blur.size", "8"),
    ("decoration.blur.special", "false"),
    ("decoration.blur.vibrancy", "0.1696"),
    ("decoration.blur.vibrancy_darkness", "0"),
    ("decoration.blur.xray", "false"),
    ("decoration.border_part_of_window", "true"),
    ("decoration.dim_around", "0.4"),
    ("decoration.dim_inactive", "false"),
    ("decoration.dim_modal", "true"),
    ("decoration.dim_special", "0.2"),
    ("decoration.dim_strength", "0.5"),
    ("decoration.fullscreen_opacity", "1"),
    ("decoration.glow.color", "ee33ccff"),
    ("decoration.glow.color_inactive", "33ccff"),
    ("decoration.glow.enabled", "false"),
    ("decoration.glow.range", "10"),
    ("decoration.glow.render_power", "3"),
    ("decoration.inactive_opacity", "1"),
    ("decoration.rounding", "0"),
    ("decoration.rounding_power", "2"),
    ("decoration.screen_shader", "[[EMPTY]]"),
    ("decoration.shadow.color", "ee1a1a1a"),
    ("decoration.shadow.color_inactive", "-1"),
    ("decoration.shadow.enabled", "true"),
    ("decoration.shadow.offset", "[0, 0]"),
    ("decoration.shadow.range", "4"),
    ("decoration.shadow.render_power", "3"),
    ("decoration.shadow.scale", "1"),
    ("decoration.shadow.sharp", "false"),
    ("dwindle.default_split_ratio", "1"),
    ("dwindle.force_split", "0"),
    ("dwindle.permanent_direction_override", "false"),
    ("dwindle.precise_mouse_move", "false"),
    ("dwindle.preserve_split", "false"),
    ("dwindle.smart_resizing", "true"),
    ("dwindle.smart_split", "false"),
    ("dwindle.special_scale_factor", "1"),
    ("dwindle.split_bias", "0"),
    ("dwindle.split_width_multiplier", "1"),
    ("dwindle.use_active_for_splits", "true"),
    ("ecosystem.enforce_permissions", "false"),
    ("ecosystem.no_donation_nag", "false"),
    ("ecosystem.no_update_news", "false"),
    ("experimental.wp_cm_1_2", "false"),
    ("general.allow_tearing", "false"),
    ("general.border_size", "1"),
    ("general.col.active_border", "ffffffff 0deg"),
    ("general.col.inactive_border", "ff444444 0deg"),
    ("general.col.nogroup_border", "ffffaaff 0deg"),
    ("general.col.nogroup_border_active", "ffff00ff 0deg"),
    ("general.extend_border_grab_area", "15"),
    ("general.float_gaps", "0 0 0 0"),
    ("general.gaps_in", "5 5 5 5"),
    ("general.gaps_out", "20 20 20 20"),
    ("general.gaps_workspaces", "0"),
    ("general.hover_icon_on_border", "true"),
    ("general.layout", "dwindle"),
    ("general.locale", ""),
    ("general.modal_parent_blocking", "true"),
    ("general.no_focus_fallback", "false"),
    ("general.resize_corner", "0"),
    ("general.resize_on_border", "false"),
    ("general.snap.border_overlap", "false"),
    ("general.snap.enabled", "false"),
    ("general.snap.monitor_gap", "10"),
    ("general.snap.respect_gaps", "false"),
    ("general.snap.window_gap", "10"),
    ("gestures.close_max_timeout", "1000"),
    ("gestures.scrolling.move_snap_cursor", "true"),
    ("gestures.scrolling.move_snap_to_grid", "true"),
    ("gestures.workspace_swipe_cancel_ratio", "0.5"),
    ("gestures.workspace_swipe_create_new", "true"),
    ("gestures.workspace_swipe_direction_lock", "true"),
    ("gestures.workspace_swipe_direction_lock_threshold", "10"),
    ("gestures.workspace_swipe_distance", "300"),
    ("gestures.workspace_swipe_forever", "false"),
    ("gestures.workspace_swipe_invert", "true"),
    ("gestures.workspace_swipe_min_speed_to_force", "30"),
    ("gestures.workspace_swipe_touch", "false"),
    ("gestures.workspace_swipe_touch_invert", "false"),
    ("gestures.workspace_swipe_use_r", "false"),
    ("group.auto_group", "true"),
    ("group.col.border_active", "66ffff00 0deg"),
    ("group.col.border_inactive", "66777700 0deg"),
    ("group.col.border_locked_active", "66775500 0deg"),
    ("group.col.border_locked_inactive", "66ff5500 0deg"),
    ("group.drag_into_group", "1"),
    ("group.focus_removed_window", "true"),
    ("group.group_on_movetoworkspace", "false"),
    ("group.groupbar.blur", "false"),
    ("group.groupbar.col.active", "66ffff00 0deg"),
    ("group.groupbar.col.inactive", "66777700 0deg"),
    ("group.groupbar.col.locked_active", "66ff5500 0deg"),
    ("group.groupbar.col.locked_inactive", "66775500 0deg"),
    ("group.groupbar.enabled", "true"),
    ("group.groupbar.font_family", "[[EMPTY]]"),
    ("group.groupbar.font_size", "8"),
    ("group.groupbar.font_weight_active", "400"),
    ("group.groupbar.font_weight_inactive", "400"),
    ("group.groupbar.gaps_in", "2"),
    ("group.groupbar.gaps_out", "2"),
    ("group.groupbar.gradient_round_only_edges", "true"),
    ("group.groupbar.gradient_rounding", "2"),
    ("group.groupbar.gradient_rounding_power", "2"),
    ("group.groupbar.gradients", "false"),
    ("group.groupbar.height", "14"),
    ("group.groupbar.indicator_gap", "0"),
    ("group.groupbar.indicator_height", "3"),
    ("group.groupbar.keep_upper_gap", "true"),
    ("group.groupbar.middle_click_close", "true"),
    ("group.groupbar.priority", "3"),
    ("group.groupbar.render_titles", "true"),
    ("group.groupbar.round_only_edges", "true"),
    ("group.groupbar.rounding", "1"),
    ("group.groupbar.rounding_power", "2"),
    ("group.groupbar.scrolling", "true"),
    ("group.groupbar.stacked", "false"),
    ("group.groupbar.text_color", "ffffffff"),
    ("group.groupbar.text_color_inactive", "-1"),
    ("group.groupbar.text_color_locked_active", "-1"),
    ("group.groupbar.text_color_locked_inactive", "-1"),
    ("group.groupbar.text_offset", "0"),
    ("group.groupbar.text_padding", "0"),
    ("group.insert_after_current", "true"),
    ("group.merge_floated_into_tiled_on_groupbar", "false"),
    ("group.merge_groups_on_drag", "true"),
    ("group.merge_groups_on_groupbar", "true"),
    ("input.accel_profile", "[[EMPTY]]"),
    ("input.emulate_discrete_scroll", "1"),
    ("input.float_switch_override_focus", "1"),
    ("input.focus_on_close", "0"),
    ("input.follow_mouse", "1"),
    ("input.follow_mouse_shrink", "0"),
    ("input.follow_mouse_threshold", "0"),
    ("input.force_no_accel", "false"),
    ("input.kb_file", "[[EMPTY]]"),
    ("input.kb_layout", "us"),
    ("input.kb_model", "[[EMPTY]]"),
    ("input.kb_options", "[[EMPTY]]"),
    ("input.kb_rules", "[[EMPTY]]"),
    ("input.kb_variant", "[[EMPTY]]"),
    ("input.left_handed", "false"),
    ("input.mouse_refocus", "true"),
    ("input.natural_scroll", "false"),
    ("input.numlock_by_default", "false"),
    ("input.off_window_axis_events", "1"),
    ("input.repeat_delay", "600"),
    ("input.repeat_rate", "25"),
    ("input.resolve_binds_by_sym", "false"),
    ("input.rotation", "0"),
    ("input.scroll_button", "0"),
    ("input.scroll_button_lock", "false"),
    ("input.scroll_factor", "1"),
    ("input.scroll_method", "[[EMPTY]]"),
    ("input.scroll_points", "[[EMPTY]]"),
    ("input.sensitivity", "0"),
    ("input.special_fallthrough", "false"),
    ("input.tablet.absolute_region_position", "false"),
    ("input.tablet.active_area_position", "[0, 0]"),
    ("input.tablet.active_area_size", "[0, 0]"),
    ("input.tablet.left_handed", "false"),
    ("input.tablet.output", "[[EMPTY]]"),
    ("input.tablet.region_position", "[0, 0]"),
    ("input.tablet.region_size", "[0, 0]"),
    ("input.tablet.relative_input", "false"),
    ("input.tablet.transform", "0"),
    ("input.touchdevice.enabled", "true"),
    ("input.touchdevice.output", "[[Auto]]"),
    ("input.touchdevice.transform", "0"),
    ("input.touchpad.clickfinger_behavior", "false"),
    ("input.touchpad.disable_while_typing", "true"),
    ("input.touchpad.drag_3fg", "0"),
    ("input.touchpad.drag_lock", "0"),
    ("input.touchpad.flip_x", "false"),
    ("input.touchpad.flip_y", "false"),
    ("input.touchpad.middle_button_emulation", "false"),
    ("input.touchpad.natural_scroll", "false"),
    ("input.touchpad.scroll_factor", "1"),
    ("input.touchpad.tap-and-drag", "true"),
    ("input.touchpad.tap-to-click", "true"),
    ("input.touchpad.tap_button_map", "[[EMPTY]]"),
    ("input.virtualkeyboard.release_pressed_on_close", "false"),
    ("input.virtualkeyboard.share_states", "2"),
    ("layout.single_window_aspect_ratio", "[0, 0]"),
    ("layout.single_window_aspect_ratio_tolerance", "0.1"),
    ("master.allow_small_split", "false"),
    ("master.always_keep_position", "false"),
    ("master.center_ignores_reserved", "false"),
    ("master.center_master_fallback", "left"),
    ("master.drop_at_cursor", "true"),
    ("master.mfact", "0.55"),
    ("master.new_on_active", "none"),
    ("master.new_on_top", "false"),
    ("master.new_status", "slave"),
    ("master.orientation", "left"),
    ("master.slave_count_for_center_master", "2"),
    ("master.smart_resizing", "true"),
    ("master.special_scale_factor", "1"),
    ("misc.allow_session_lock_restore", "false"),
    ("misc.always_follow_on_dnd", "true"),
    ("misc.animate_manual_resizes", "false"),
    ("misc.animate_mouse_windowdragging", "false"),
    ("misc.anr_missed_pings", "5"),
    ("misc.background_color", "ff111111"),
    ("misc.close_special_on_empty", "true"),
    ("misc.col.splash", "55ffffff"),
    ("misc.disable_autoreload", "false"),
    ("misc.disable_hyprland_guiutils_check", "false"),
    ("misc.disable_hyprland_logo", "false"),
    ("misc.disable_scale_notification", "false"),
    ("misc.disable_splash_rendering", "false"),
    ("misc.disable_watchdog_warning", "false"),
    ("misc.disable_xdg_env_checks", "false"),
    ("misc.enable_anr_dialog", "true"),
    ("misc.enable_swallow", "false"),
    ("misc.exit_window_retains_fullscreen", "false"),
    ("misc.focus_on_activate", "false"),
    ("misc.font_family", "Sans"),
    ("misc.force_default_wallpaper", "-1"),
    ("misc.initial_workspace_tracking", "1"),
    ("misc.key_press_enables_dpms", "false"),
    ("misc.layers_hog_keyboard_focus", "true"),
    ("misc.lockdead_screen_delay", "1000"),
    ("misc.middle_click_paste", "true"),
    ("misc.mouse_move_enables_dpms", "false"),
    ("misc.mouse_move_focuses_monitor", "true"),
    ("misc.name_vk_after_proc", "true"),
    ("misc.on_focus_under_fullscreen", "2"),
    ("misc.render_unfocused_fps", "15"),
    ("misc.screencopy_force_8b", "true"),
    ("misc.session_lock_xray", "false"),
    ("misc.size_limits_tiled", "false"),
    ("misc.splash_font_family", "[[EMPTY]]"),
    ("misc.swallow_exception_regex", "[[EMPTY]]"),
    ("misc.swallow_regex", "[[EMPTY]]"),
    ("misc.vrr", "0"),
    ("opengl.nvidia_anti_flicker", "true"),
    ("quirks.prefer_hdr", "0"),
    ("quirks.skip_non_kms_dmabuf_formats", "false"),
    ("render.cm_auto_hdr", "1"),
    ("render.cm_enabled", "true"),
    ("render.cm_sdr_eotf", "default"),
    ("render.commit_timing_enabled", "true"),
    ("render.ctm_animation", "2"),
    ("render.direct_scanout", "0"),
    ("render.expand_undersized_textures", "true"),
    ("render.fp16_sdr_tf", "0"),
    ("render.icc_vcgt_enabled", "true"),
    ("render.keep_unmodified_copy", "2"),
    ("render.new_render_scheduling", "false"),
    ("render.non_shader_cm", "3"),
    ("render.non_shader_cm_interop", "2"),
    ("render.send_content_type", "true"),
    ("render.use_fp16", "2"),
    ("render.use_shader_blur_blend", "false"),
    ("render.xp_mode", "false"),
    ("scrolling.column_width", "0.5"),
    ("scrolling.direction", "right"),
    ("scrolling.explicit_column_widths", "0.333, 0.5, 0.667, 1.0"),
    ("scrolling.focus_fit_method", "1"),
    ("scrolling.follow_focus", "true"),
    ("scrolling.follow_min_visible", "0.4"),
    ("scrolling.fullscreen_on_one_column", "true"),
    ("scrolling.wrap_focus", "true"),
    ("scrolling.wrap_swapcol", "true"),
    ("xwayland.create_abstract_socket", "false"),
    ("xwayland.enabled", "true"),
    ("xwayland.force_zero_scaling", "false"),
    ("xwayland.use_nearest_neighbor", "true"),
];
